# Generated by Django 4.1.2 on 2022-10-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Foodtable',
        ),
    ]
