# Generated by Django 4.1.2 on 2022-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_rename_table_foodtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercisetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=10)),
            ],
        ),
    ]
